// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: lock.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLeaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// owner_id is used only when no authenticated workload identity is present.
	// With mTLS, the server derives the effective owner from the client cert.
	OwnerId string `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// ttl_seconds controls how long the lease remains valid without renewal.
	TtlSeconds    int64 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeaseRequest) Reset() {
	*x = CreateLeaseRequest{}
	mi := &file_lock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeaseRequest) ProtoMessage() {}

func (x *CreateLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeaseRequest.ProtoReflect.Descriptor instead.
func (*CreateLeaseRequest) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLeaseRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateLeaseRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreateLeaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lease_id is the server-assigned session identifier used by later RPCs.
	LeaseId       uint64 `protobuf:"varint,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	TtlSeconds    int64  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeaseResponse) Reset() {
	*x = CreateLeaseResponse{}
	mi := &file_lock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeaseResponse) ProtoMessage() {}

func (x *CreateLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeaseResponse.ProtoReflect.Descriptor instead.
func (*CreateLeaseResponse) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLeaseResponse) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *CreateLeaseResponse) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type RenewLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       uint64                 `protobuf:"varint,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseRequest) Reset() {
	*x = RenewLeaseRequest{}
	mi := &file_lock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseRequest) ProtoMessage() {}

func (x *RenewLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewLeaseRequest) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{2}
}

func (x *RenewLeaseRequest) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

type RenewLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TtlSeconds    int64                  `protobuf:"varint,1,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseResponse) Reset() {
	*x = RenewLeaseResponse{}
	mi := &file_lock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseResponse) ProtoMessage() {}

func (x *RenewLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewLeaseResponse) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{3}
}

func (x *RenewLeaseResponse) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       uint64                 `protobuf:"varint,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_lock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       uint64                 `protobuf:"varint,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_lock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *HeartbeatResponse) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type AcquireLockRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	LockName string                 `protobuf:"bytes,1,opt,name=lock_name,json=lockName,proto3" json:"lock_name,omitempty"`
	// owner_id is overridden by mTLS-derived workload identity when available.
	OwnerId       string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	LeaseId       uint64 `protobuf:"varint,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLockRequest) Reset() {
	*x = AcquireLockRequest{}
	mi := &file_lock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockRequest) ProtoMessage() {}

func (x *AcquireLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockRequest.ProtoReflect.Descriptor instead.
func (*AcquireLockRequest) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{6}
}

func (x *AcquireLockRequest) GetLockName() string {
	if x != nil {
		return x.LockName
	}
	return ""
}

func (x *AcquireLockRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *AcquireLockRequest) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

type AcquireLockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// fencing_token is globally monotonic. Callers should include it in
	// downstream writes so stale workers can be rejected.
	FencingToken    uint64 `protobuf:"varint,1,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	LeaseTtlSeconds int64  `protobuf:"varint,2,opt,name=lease_ttl_seconds,json=leaseTtlSeconds,proto3" json:"lease_ttl_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcquireLockResponse) Reset() {
	*x = AcquireLockResponse{}
	mi := &file_lock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockResponse) ProtoMessage() {}

func (x *AcquireLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockResponse.ProtoReflect.Descriptor instead.
func (*AcquireLockResponse) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{7}
}

func (x *AcquireLockResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *AcquireLockResponse) GetLeaseTtlSeconds() int64 {
	if x != nil {
		return x.LeaseTtlSeconds
	}
	return 0
}

type ReleaseLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockName      string                 `protobuf:"bytes,1,opt,name=lock_name,json=lockName,proto3" json:"lock_name,omitempty"`
	LeaseId       uint64                 `protobuf:"varint,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockRequest) Reset() {
	*x = ReleaseLockRequest{}
	mi := &file_lock_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockRequest) ProtoMessage() {}

func (x *ReleaseLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseLockRequest) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseLockRequest) GetLockName() string {
	if x != nil {
		return x.LockName
	}
	return ""
}

func (x *ReleaseLockRequest) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

type ReleaseLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockResponse) Reset() {
	*x = ReleaseLockResponse{}
	mi := &file_lock_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockResponse) ProtoMessage() {}

func (x *ReleaseLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseLockResponse) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseLockResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_lock_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{10}
}

type GetStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                     // This node's ID
	IsLeader          bool                   `protobuf:"varint,2,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`                              // Is this node the leader?
	LeaderAddress     string                 `protobuf:"bytes,3,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`                // Current leader address
	ClusterSize       int32                  `protobuf:"varint,4,opt,name=cluster_size,json=clusterSize,proto3" json:"cluster_size,omitempty"`                     // Number of nodes in cluster
	State             string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`                                                     // Raft state: "leader", "follower", "candidate"
	Stats             *Stats                 `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`                                                     // FSM statistics
	GrpcAddress       string                 `protobuf:"bytes,7,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`                      // This node's gRPC address
	Members           []*ClusterMember       `protobuf:"bytes,9,rep,name=members,proto3" json:"members,omitempty"`                                                 // Replicated node metadata for discovery
	LeaderGrpcAddress string                 `protobuf:"bytes,10,opt,name=leader_grpc_address,json=leaderGrpcAddress,proto3" json:"leader_grpc_address,omitempty"` // Client-facing gRPC address of the leader
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_lock_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetStatusResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *GetStatusResponse) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

func (x *GetStatusResponse) GetClusterSize() int32 {
	if x != nil {
		return x.ClusterSize
	}
	return 0
}

func (x *GetStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetStatusResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetStatusResponse) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

func (x *GetStatusResponse) GetMembers() []*ClusterMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetStatusResponse) GetLeaderGrpcAddress() string {
	if x != nil {
		return x.LeaderGrpcAddress
	}
	return ""
}

// LeaderHint is attached to "not leader" gRPC errors as structured status
// details so clients do not need to parse free-form error messages.
type LeaderHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrpcAddress   string                 `protobuf:"bytes,1,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	RaftAddress   string                 `protobuf:"bytes,2,opt,name=raft_address,json=raftAddress,proto3" json:"raft_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderHint) Reset() {
	*x = LeaderHint{}
	mi := &file_lock_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderHint) ProtoMessage() {}

func (x *LeaderHint) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderHint.ProtoReflect.Descriptor instead.
func (*LeaderHint) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{12}
}

func (x *LeaderHint) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

func (x *LeaderHint) GetRaftAddress() string {
	if x != nil {
		return x.RaftAddress
	}
	return ""
}

type Stats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Leases         int32                  `protobuf:"varint,1,opt,name=leases,proto3" json:"leases,omitempty"`                                       // Number of active leases
	Locks          int32                  `protobuf:"varint,2,opt,name=locks,proto3" json:"locks,omitempty"`                                         // Number of active locks
	FencingCounter uint64                 `protobuf:"varint,3,opt,name=fencing_counter,json=fencingCounter,proto3" json:"fencing_counter,omitempty"` // Current fencing counter value
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_lock_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{13}
}

func (x *Stats) GetLeases() int32 {
	if x != nil {
		return x.Leases
	}
	return 0
}

func (x *Stats) GetLocks() int32 {
	if x != nil {
		return x.Locks
	}
	return 0
}

func (x *Stats) GetFencingCounter() uint64 {
	if x != nil {
		return x.FencingCounter
	}
	return 0
}

type ClusterMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id is the Raft ServerID.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// raft_address is used only for peer-to-peer Raft traffic.
	RaftAddress string `protobuf:"bytes,2,opt,name=raft_address,json=raftAddress,proto3" json:"raft_address,omitempty"`
	// grpc_address is used by clients/admin tools for RPC traffic.
	GrpcAddress   string `protobuf:"bytes,3,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMember) Reset() {
	*x = ClusterMember{}
	mi := &file_lock_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMember) ProtoMessage() {}

func (x *ClusterMember) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMember.ProtoReflect.Descriptor instead.
func (*ClusterMember) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{14}
}

func (x *ClusterMember) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ClusterMember) GetRaftAddress() string {
	if x != nil {
		return x.RaftAddress
	}
	return ""
}

func (x *ClusterMember) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

type JoinNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RaftAddress   string                 `protobuf:"bytes,2,opt,name=raft_address,json=raftAddress,proto3" json:"raft_address,omitempty"`
	GrpcAddress   string                 `protobuf:"bytes,3,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinNodeRequest) Reset() {
	*x = JoinNodeRequest{}
	mi := &file_lock_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNodeRequest) ProtoMessage() {}

func (x *JoinNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNodeRequest.ProtoReflect.Descriptor instead.
func (*JoinNodeRequest) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{15}
}

func (x *JoinNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinNodeRequest) GetRaftAddress() string {
	if x != nil {
		return x.RaftAddress
	}
	return ""
}

func (x *JoinNodeRequest) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

type JoinNodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Joined            bool                   `protobuf:"varint,1,opt,name=joined,proto3" json:"joined,omitempty"`
	LeaderGrpcAddress string                 `protobuf:"bytes,2,opt,name=leader_grpc_address,json=leaderGrpcAddress,proto3" json:"leader_grpc_address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JoinNodeResponse) Reset() {
	*x = JoinNodeResponse{}
	mi := &file_lock_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNodeResponse) ProtoMessage() {}

func (x *JoinNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNodeResponse.ProtoReflect.Descriptor instead.
func (*JoinNodeResponse) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{16}
}

func (x *JoinNodeResponse) GetJoined() bool {
	if x != nil {
		return x.Joined
	}
	return false
}

func (x *JoinNodeResponse) GetLeaderGrpcAddress() string {
	if x != nil {
		return x.LeaderGrpcAddress
	}
	return ""
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_lock_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RemoveNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeResponse) Reset() {
	*x = RemoveNodeResponse{}
	mi := &file_lock_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponse) ProtoMessage() {}

func (x *RemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveNodeResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

var File_lock_proto protoreflect.FileDescriptor

const file_lock_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"lock.proto\x12\tclavis.v1\"P\n" +
	"\x12CreateLeaseRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"Q\n" +
	"\x13CreateLeaseResponse\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\x04R\aleaseId\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\".\n" +
	"\x11RenewLeaseRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\x04R\aleaseId\"5\n" +
	"\x12RenewLeaseResponse\x12\x1f\n" +
	"\vttl_seconds\x18\x01 \x01(\x03R\n" +
	"ttlSeconds\"-\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\x04R\aleaseId\"O\n" +
	"\x11HeartbeatResponse\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\x04R\aleaseId\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"g\n" +
	"\x12AcquireLockRequest\x12\x1b\n" +
	"\tlock_name\x18\x01 \x01(\tR\blockName\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\x04R\aleaseId\"f\n" +
	"\x13AcquireLockResponse\x12#\n" +
	"\rfencing_token\x18\x01 \x01(\x04R\ffencingToken\x12*\n" +
	"\x11lease_ttl_seconds\x18\x02 \x01(\x03R\x0fleaseTtlSeconds\"L\n" +
	"\x12ReleaseLockRequest\x12\x1b\n" +
	"\tlock_name\x18\x01 \x01(\tR\blockName\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\x04R\aleaseId\"1\n" +
	"\x13ReleaseLockResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"\x12\n" +
	"\x10GetStatusRequest\"\xd8\x02\n" +
	"\x11GetStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tis_leader\x18\x02 \x01(\bR\bisLeader\x12%\n" +
	"\x0eleader_address\x18\x03 \x01(\tR\rleaderAddress\x12!\n" +
	"\fcluster_size\x18\x04 \x01(\x05R\vclusterSize\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12&\n" +
	"\x05stats\x18\x06 \x01(\v2\x10.clavis.v1.StatsR\x05stats\x12!\n" +
	"\fgrpc_address\x18\a \x01(\tR\vgrpcAddress\x122\n" +
	"\amembers\x18\t \x03(\v2\x18.clavis.v1.ClusterMemberR\amembers\x12.\n" +
	"\x13leader_grpc_address\x18\n" +
	" \x01(\tR\x11leaderGrpcAddress\"R\n" +
	"\n" +
	"LeaderHint\x12!\n" +
	"\fgrpc_address\x18\x01 \x01(\tR\vgrpcAddress\x12!\n" +
	"\fraft_address\x18\x02 \x01(\tR\vraftAddress\"^\n" +
	"\x05Stats\x12\x16\n" +
	"\x06leases\x18\x01 \x01(\x05R\x06leases\x12\x14\n" +
	"\x05locks\x18\x02 \x01(\x05R\x05locks\x12'\n" +
	"\x0ffencing_counter\x18\x03 \x01(\x04R\x0efencingCounter\"n\n" +
	"\rClusterMember\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fraft_address\x18\x02 \x01(\tR\vraftAddress\x12!\n" +
	"\fgrpc_address\x18\x03 \x01(\tR\vgrpcAddress\"p\n" +
	"\x0fJoinNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fraft_address\x18\x02 \x01(\tR\vraftAddress\x12!\n" +
	"\fgrpc_address\x18\x03 \x01(\tR\vgrpcAddress\"Z\n" +
	"\x10JoinNodeResponse\x12\x16\n" +
	"\x06joined\x18\x01 \x01(\bR\x06joined\x12.\n" +
	"\x13leader_grpc_address\x18\x02 \x01(\tR\x11leaderGrpcAddress\",\n" +
	"\x11RemoveNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\".\n" +
	"\x12RemoveNodeResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved2\xd6\x03\n" +
	"\vLockService\x12L\n" +
	"\vCreateLease\x12\x1d.clavis.v1.CreateLeaseRequest\x1a\x1e.clavis.v1.CreateLeaseResponse\x12I\n" +
	"\n" +
	"RenewLease\x12\x1c.clavis.v1.RenewLeaseRequest\x1a\x1d.clavis.v1.RenewLeaseResponse\x12J\n" +
	"\tHeartbeat\x12\x1b.clavis.v1.HeartbeatRequest\x1a\x1c.clavis.v1.HeartbeatResponse(\x010\x01\x12L\n" +
	"\vAcquireLock\x12\x1d.clavis.v1.AcquireLockRequest\x1a\x1e.clavis.v1.AcquireLockResponse\x12L\n" +
	"\vReleaseLock\x12\x1d.clavis.v1.ReleaseLockRequest\x1a\x1e.clavis.v1.ReleaseLockResponse\x12F\n" +
	"\tGetStatus\x12\x1b.clavis.v1.GetStatusRequest\x1a\x1c.clavis.v1.GetStatusResponse2\xe6\x01\n" +
	"\fAdminService\x12F\n" +
	"\tGetStatus\x12\x1b.clavis.v1.GetStatusRequest\x1a\x1c.clavis.v1.GetStatusResponse\x12C\n" +
	"\bJoinNode\x12\x1a.clavis.v1.JoinNodeRequest\x1a\x1b.clavis.v1.JoinNodeResponse\x12I\n" +
	"\n" +
	"RemoveNode\x12\x1c.clavis.v1.RemoveNodeRequest\x1a\x1d.clavis.v1.RemoveNodeResponseB\x1bZ\x19github.com/Mfon-19/clavisb\x06proto3"

var (
	file_lock_proto_rawDescOnce sync.Once
	file_lock_proto_rawDescData []byte
)

func file_lock_proto_rawDescGZIP() []byte {
	file_lock_proto_rawDescOnce.Do(func() {
		file_lock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lock_proto_rawDesc), len(file_lock_proto_rawDesc)))
	})
	return file_lock_proto_rawDescData
}

var file_lock_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_lock_proto_goTypes = []any{
	(*CreateLeaseRequest)(nil),  // 0: clavis.v1.CreateLeaseRequest
	(*CreateLeaseResponse)(nil), // 1: clavis.v1.CreateLeaseResponse
	(*RenewLeaseRequest)(nil),   // 2: clavis.v1.RenewLeaseRequest
	(*RenewLeaseResponse)(nil),  // 3: clavis.v1.RenewLeaseResponse
	(*HeartbeatRequest)(nil),    // 4: clavis.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 5: clavis.v1.HeartbeatResponse
	(*AcquireLockRequest)(nil),  // 6: clavis.v1.AcquireLockRequest
	(*AcquireLockResponse)(nil), // 7: clavis.v1.AcquireLockResponse
	(*ReleaseLockRequest)(nil),  // 8: clavis.v1.ReleaseLockRequest
	(*ReleaseLockResponse)(nil), // 9: clavis.v1.ReleaseLockResponse
	(*GetStatusRequest)(nil),    // 10: clavis.v1.GetStatusRequest
	(*GetStatusResponse)(nil),   // 11: clavis.v1.GetStatusResponse
	(*LeaderHint)(nil),          // 12: clavis.v1.LeaderHint
	(*Stats)(nil),               // 13: clavis.v1.Stats
	(*ClusterMember)(nil),       // 14: clavis.v1.ClusterMember
	(*JoinNodeRequest)(nil),     // 15: clavis.v1.JoinNodeRequest
	(*JoinNodeResponse)(nil),    // 16: clavis.v1.JoinNodeResponse
	(*RemoveNodeRequest)(nil),   // 17: clavis.v1.RemoveNodeRequest
	(*RemoveNodeResponse)(nil),  // 18: clavis.v1.RemoveNodeResponse
}
var file_lock_proto_depIdxs = []int32{
	13, // 0: clavis.v1.GetStatusResponse.stats:type_name -> clavis.v1.Stats
	14, // 1: clavis.v1.GetStatusResponse.members:type_name -> clavis.v1.ClusterMember
	0,  // 2: clavis.v1.LockService.CreateLease:input_type -> clavis.v1.CreateLeaseRequest
	2,  // 3: clavis.v1.LockService.RenewLease:input_type -> clavis.v1.RenewLeaseRequest
	4,  // 4: clavis.v1.LockService.Heartbeat:input_type -> clavis.v1.HeartbeatRequest
	6,  // 5: clavis.v1.LockService.AcquireLock:input_type -> clavis.v1.AcquireLockRequest
	8,  // 6: clavis.v1.LockService.ReleaseLock:input_type -> clavis.v1.ReleaseLockRequest
	10, // 7: clavis.v1.LockService.GetStatus:input_type -> clavis.v1.GetStatusRequest
	10, // 8: clavis.v1.AdminService.GetStatus:input_type -> clavis.v1.GetStatusRequest
	15, // 9: clavis.v1.AdminService.JoinNode:input_type -> clavis.v1.JoinNodeRequest
	17, // 10: clavis.v1.AdminService.RemoveNode:input_type -> clavis.v1.RemoveNodeRequest
	1,  // 11: clavis.v1.LockService.CreateLease:output_type -> clavis.v1.CreateLeaseResponse
	3,  // 12: clavis.v1.LockService.RenewLease:output_type -> clavis.v1.RenewLeaseResponse
	5,  // 13: clavis.v1.LockService.Heartbeat:output_type -> clavis.v1.HeartbeatResponse
	7,  // 14: clavis.v1.LockService.AcquireLock:output_type -> clavis.v1.AcquireLockResponse
	9,  // 15: clavis.v1.LockService.ReleaseLock:output_type -> clavis.v1.ReleaseLockResponse
	11, // 16: clavis.v1.LockService.GetStatus:output_type -> clavis.v1.GetStatusResponse
	11, // 17: clavis.v1.AdminService.GetStatus:output_type -> clavis.v1.GetStatusResponse
	16, // 18: clavis.v1.AdminService.JoinNode:output_type -> clavis.v1.JoinNodeResponse
	18, // 19: clavis.v1.AdminService.RemoveNode:output_type -> clavis.v1.RemoveNodeResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_lock_proto_init() }
func file_lock_proto_init() {
	if File_lock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lock_proto_rawDesc), len(file_lock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_lock_proto_goTypes,
		DependencyIndexes: file_lock_proto_depIdxs,
		MessageInfos:      file_lock_proto_msgTypes,
	}.Build()
	File_lock_proto = out.File
	file_lock_proto_goTypes = nil
	file_lock_proto_depIdxs = nil
}
