// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: internal/raftlog/command.proto

package raftlog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandType identifies which command payload is present in CommandWrapper.
// These values are persisted in Raft logs; never reuse removed numbers.
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED     CommandType = 0
	CommandType_COMMAND_TYPE_CREATE_LEASE    CommandType = 1
	CommandType_COMMAND_TYPE_RENEW_LEASE     CommandType = 2
	CommandType_COMMAND_TYPE_ACQUIRE_LOCK    CommandType = 3
	CommandType_COMMAND_TYPE_RELEASE_LOCK    CommandType = 4
	CommandType_COMMAND_TYPE_EXPIRE_LEASE    CommandType = 5
	CommandType_COMMAND_TYPE_UPSERT_ENDPOINT CommandType = 6
	CommandType_COMMAND_TYPE_REMOVE_ENDPOINT CommandType = 7
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_CREATE_LEASE",
		2: "COMMAND_TYPE_RENEW_LEASE",
		3: "COMMAND_TYPE_ACQUIRE_LOCK",
		4: "COMMAND_TYPE_RELEASE_LOCK",
		5: "COMMAND_TYPE_EXPIRE_LEASE",
		6: "COMMAND_TYPE_UPSERT_ENDPOINT",
		7: "COMMAND_TYPE_REMOVE_ENDPOINT",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":     0,
		"COMMAND_TYPE_CREATE_LEASE":    1,
		"COMMAND_TYPE_RENEW_LEASE":     2,
		"COMMAND_TYPE_ACQUIRE_LOCK":    3,
		"COMMAND_TYPE_RELEASE_LOCK":    4,
		"COMMAND_TYPE_EXPIRE_LEASE":    5,
		"COMMAND_TYPE_UPSERT_ENDPOINT": 6,
		"COMMAND_TYPE_REMOVE_ENDPOINT": 7,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_raftlog_command_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_internal_raftlog_command_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_internal_raftlog_command_proto_rawDescGZIP(), []int{0}
}

// CreateLeaseCommand creates a new lease. The service supplies created_at so
// every node computes the same expiry time while replaying the Raft log
type CreateLeaseCommand struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OwnerId          string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TtlNanos         int64                  `protobuf:"varint,2,opt,name=ttl_nanos,json=ttlNanos,proto3" json:"ttl_nanos,omitempty"`
	CreateAtUnixNano int64                  `protobuf:"varint,3,opt,name=create_at_unix_nano,json=createAtUnixNano,proto3" json:"create_at_unix_nano,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateLeaseCommand) Reset() {
	*x = CreateLeaseCommand{}
	mi := &file_internal_raftlog_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeaseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeaseCommand) ProtoMessage() {}

func (x *CreateLeaseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raftlog_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeaseCommand.ProtoReflect.Descriptor instead.
func (*CreateLeaseCommand) Descriptor() ([]byte, []int) {
	return file_internal_raftlog_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLeaseCommand) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateLeaseCommand) GetTtlNanos() int64 {
	if x != nil {
		return x.TtlNanos
	}
	return 0
}

func (x *CreateLeaseCommand) GetCreateAtUnixNano() int64 {
	if x != nil {
		return x.CreateAtUnixNano
	}
	return 0
}

// RenewLeaseCommand renews an existing lease relative to the proposal time.
type RenewLeaseCommand struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LeaseId           uint64                 `protobuf:"varint,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	RenewedAtUnixNano int64                  `protobuf:"varint,2,opt,name=renewed_at_unix_nano,json=renewedAtUnixNano,proto3" json:"renewed_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RenewLeaseCommand) Reset() {
	*x = RenewLeaseCommand{}
	mi := &file_internal_raftlog_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseCommand) ProtoMessage() {}

func (x *RenewLeaseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raftlog_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseCommand.ProtoReflect.Descriptor instead.
func (*RenewLeaseCommand) Descriptor() ([]byte, []int) {
	return file_internal_raftlog_command_proto_rawDescGZIP(), []int{1}
}

func (x *RenewLeaseCommand) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *RenewLeaseCommand) GetRenewedAtUnixNano() int64 {
	if x != nil {
		return x.RenewedAtUnixNano
	}
	return 0
}

// AcquireLockCommand acquires a lock with fencing. The timestamp lets the FSM
// reject acquisitions whose lease had already expired at proposal time.
type AcquireLockCommand struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LockName           string                 `protobuf:"bytes,1,opt,name=lock_name,json=lockName,proto3" json:"lock_name,omitempty"`
	OwnerId            string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	LeaseId            uint64                 `protobuf:"varint,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	AcquiredAtUnixNano int64                  `protobuf:"varint,4,opt,name=acquired_at_unix_nano,json=acquiredAtUnixNano,proto3" json:"acquired_at_unix_nano,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AcquireLockCommand) Reset() {
	*x = AcquireLockCommand{}
	mi := &file_internal_raftlog_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockCommand) ProtoMessage() {}

func (x *AcquireLockCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raftlog_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockCommand.ProtoReflect.Descriptor instead.
func (*AcquireLockCommand) Descriptor() ([]byte, []int) {
	return file_internal_raftlog_command_proto_rawDescGZIP(), []int{2}
}

func (x *AcquireLockCommand) GetLockName() string {
	if x != nil {
		return x.LockName
	}
	return ""
}

func (x *AcquireLockCommand) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *AcquireLockCommand) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *AcquireLockCommand) GetAcquiredAtUnixNano() int64 {
	if x != nil {
		return x.AcquiredAtUnixNano
	}
	return 0
}

// ReleaseLockCommand releases a lock held by a lease.
type ReleaseLockCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockName      string                 `protobuf:"bytes,1,opt,name=lock_name,json=lockName,proto3" json:"lock_name,omitempty"`
	LeaseId       uint64                 `protobuf:"varint,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockCommand) Reset() {
	*x = ReleaseLockCommand{}
	mi := &file_internal_raftlog_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockCommand) ProtoMessage() {}

func (x *ReleaseLockCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raftlog_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockCommand.ProtoReflect.Descriptor instead.
func (*ReleaseLockCommand) Descriptor() ([]byte, []int) {
	return file_internal_raftlog_command_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseLockCommand) GetLockName() string {
	if x != nil {
		return x.LockName
	}
	return ""
}

func (x *ReleaseLockCommand) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

// ExpireLeaseCommand expires a lease and releases all its locks. If a renewal
// committed first, the FSM no-ops this command instead of deleting live state.
type ExpireLeaseCommand struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LeaseId           uint64                 `protobuf:"varint,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ExpiredAtUnixNano int64                  `protobuf:"varint,2,opt,name=expired_at_unix_nano,json=expiredAtUnixNano,proto3" json:"expired_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExpireLeaseCommand) Reset() {
	*x = ExpireLeaseCommand{}
	mi := &file_internal_raftlog_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireLeaseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireLeaseCommand) ProtoMessage() {}

func (x *ExpireLeaseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raftlog_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireLeaseCommand.ProtoReflect.Descriptor instead.
func (*ExpireLeaseCommand) Descriptor() ([]byte, []int) {
	return file_internal_raftlog_command_proto_rawDescGZIP(), []int{4}
}

func (x *ExpireLeaseCommand) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *ExpireLeaseCommand) GetExpiredAtUnixNano() int64 {
	if x != nil {
		return x.ExpiredAtUnixNano
	}
	return 0
}

// UpsertEndpointCommand stores client-facing gRPC endpoint metadata by node ID.
// Raft configuration remains the source of truth for actual membership.
type UpsertEndpointCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	GrpcAddress   string                 `protobuf:"bytes,2,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEndpointCommand) Reset() {
	*x = UpsertEndpointCommand{}
	mi := &file_internal_raftlog_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEndpointCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEndpointCommand) ProtoMessage() {}

func (x *UpsertEndpointCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raftlog_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEndpointCommand.ProtoReflect.Descriptor instead.
func (*UpsertEndpointCommand) Descriptor() ([]byte, []int) {
	return file_internal_raftlog_command_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertEndpointCommand) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpsertEndpointCommand) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

// RemoveEndpointCommand deletes stored endpoint metadata for a node ID.
// This is best-effort cleanup; Raft membership is enforced separately.
type RemoveEndpointCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEndpointCommand) Reset() {
	*x = RemoveEndpointCommand{}
	mi := &file_internal_raftlog_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEndpointCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEndpointCommand) ProtoMessage() {}

func (x *RemoveEndpointCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raftlog_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEndpointCommand.ProtoReflect.Descriptor instead.
func (*RemoveEndpointCommand) Descriptor() ([]byte, []int) {
	return file_internal_raftlog_command_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveEndpointCommand) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// CommandWrapper is the exact message serialized into each Raft log entry.
// The explicit type is redundant with the oneof, but it keeps tracing and
// switch statements simple and stable across generated-code changes.
type CommandWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=raftlog.CommandType" json:"type,omitempty"`
	// Only one of these will be set based on type
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*CommandWrapper_CreateLease
	//	*CommandWrapper_RenewLease
	//	*CommandWrapper_AcquireLock
	//	*CommandWrapper_ReleaseLock
	//	*CommandWrapper_ExpireLease
	//	*CommandWrapper_UpsertEndpoint
	//	*CommandWrapper_RemoveEndpoint
	Payload       isCommandWrapper_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandWrapper) Reset() {
	*x = CommandWrapper{}
	mi := &file_internal_raftlog_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandWrapper) ProtoMessage() {}

func (x *CommandWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raftlog_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandWrapper.ProtoReflect.Descriptor instead.
func (*CommandWrapper) Descriptor() ([]byte, []int) {
	return file_internal_raftlog_command_proto_rawDescGZIP(), []int{7}
}

func (x *CommandWrapper) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *CommandWrapper) GetPayload() isCommandWrapper_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CommandWrapper) GetCreateLease() *CreateLeaseCommand {
	if x != nil {
		if x, ok := x.Payload.(*CommandWrapper_CreateLease); ok {
			return x.CreateLease
		}
	}
	return nil
}

func (x *CommandWrapper) GetRenewLease() *RenewLeaseCommand {
	if x != nil {
		if x, ok := x.Payload.(*CommandWrapper_RenewLease); ok {
			return x.RenewLease
		}
	}
	return nil
}

func (x *CommandWrapper) GetAcquireLock() *AcquireLockCommand {
	if x != nil {
		if x, ok := x.Payload.(*CommandWrapper_AcquireLock); ok {
			return x.AcquireLock
		}
	}
	return nil
}

func (x *CommandWrapper) GetReleaseLock() *ReleaseLockCommand {
	if x != nil {
		if x, ok := x.Payload.(*CommandWrapper_ReleaseLock); ok {
			return x.ReleaseLock
		}
	}
	return nil
}

func (x *CommandWrapper) GetExpireLease() *ExpireLeaseCommand {
	if x != nil {
		if x, ok := x.Payload.(*CommandWrapper_ExpireLease); ok {
			return x.ExpireLease
		}
	}
	return nil
}

func (x *CommandWrapper) GetUpsertEndpoint() *UpsertEndpointCommand {
	if x != nil {
		if x, ok := x.Payload.(*CommandWrapper_UpsertEndpoint); ok {
			return x.UpsertEndpoint
		}
	}
	return nil
}

func (x *CommandWrapper) GetRemoveEndpoint() *RemoveEndpointCommand {
	if x != nil {
		if x, ok := x.Payload.(*CommandWrapper_RemoveEndpoint); ok {
			return x.RemoveEndpoint
		}
	}
	return nil
}

type isCommandWrapper_Payload interface {
	isCommandWrapper_Payload()
}

type CommandWrapper_CreateLease struct {
	CreateLease *CreateLeaseCommand `protobuf:"bytes,2,opt,name=create_lease,json=createLease,proto3,oneof"`
}

type CommandWrapper_RenewLease struct {
	RenewLease *RenewLeaseCommand `protobuf:"bytes,3,opt,name=renew_lease,json=renewLease,proto3,oneof"`
}

type CommandWrapper_AcquireLock struct {
	AcquireLock *AcquireLockCommand `protobuf:"bytes,4,opt,name=acquire_lock,json=acquireLock,proto3,oneof"`
}

type CommandWrapper_ReleaseLock struct {
	ReleaseLock *ReleaseLockCommand `protobuf:"bytes,5,opt,name=release_lock,json=releaseLock,proto3,oneof"`
}

type CommandWrapper_ExpireLease struct {
	ExpireLease *ExpireLeaseCommand `protobuf:"bytes,6,opt,name=expire_lease,json=expireLease,proto3,oneof"`
}

type CommandWrapper_UpsertEndpoint struct {
	UpsertEndpoint *UpsertEndpointCommand `protobuf:"bytes,7,opt,name=upsert_endpoint,json=upsertEndpoint,proto3,oneof"`
}

type CommandWrapper_RemoveEndpoint struct {
	RemoveEndpoint *RemoveEndpointCommand `protobuf:"bytes,8,opt,name=remove_endpoint,json=removeEndpoint,proto3,oneof"`
}

func (*CommandWrapper_CreateLease) isCommandWrapper_Payload() {}

func (*CommandWrapper_RenewLease) isCommandWrapper_Payload() {}

func (*CommandWrapper_AcquireLock) isCommandWrapper_Payload() {}

func (*CommandWrapper_ReleaseLock) isCommandWrapper_Payload() {}

func (*CommandWrapper_ExpireLease) isCommandWrapper_Payload() {}

func (*CommandWrapper_UpsertEndpoint) isCommandWrapper_Payload() {}

func (*CommandWrapper_RemoveEndpoint) isCommandWrapper_Payload() {}

var File_internal_raftlog_command_proto protoreflect.FileDescriptor

const file_internal_raftlog_command_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/raftlog/command.proto\x12\araftlog\"{\n" +
	"\x12CreateLeaseCommand\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1b\n" +
	"\tttl_nanos\x18\x02 \x01(\x03R\bttlNanos\x12-\n" +
	"\x13create_at_unix_nano\x18\x03 \x01(\x03R\x10createAtUnixNano\"_\n" +
	"\x11RenewLeaseCommand\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\x04R\aleaseId\x12/\n" +
	"\x14renewed_at_unix_nano\x18\x02 \x01(\x03R\x11renewedAtUnixNano\"\x9a\x01\n" +
	"\x12AcquireLockCommand\x12\x1b\n" +
	"\tlock_name\x18\x01 \x01(\tR\blockName\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\x04R\aleaseId\x121\n" +
	"\x15acquired_at_unix_nano\x18\x04 \x01(\x03R\x12acquiredAtUnixNano\"L\n" +
	"\x12ReleaseLockCommand\x12\x1b\n" +
	"\tlock_name\x18\x01 \x01(\tR\blockName\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\x04R\aleaseId\"`\n" +
	"\x12ExpireLeaseCommand\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\x04R\aleaseId\x12/\n" +
	"\x14expired_at_unix_nano\x18\x02 \x01(\x03R\x11expiredAtUnixNano\"S\n" +
	"\x15UpsertEndpointCommand\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fgrpc_address\x18\x02 \x01(\tR\vgrpcAddress\"0\n" +
	"\x15RemoveEndpointCommand\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xa2\x04\n" +
	"\x0eCommandWrapper\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.raftlog.CommandTypeR\x04type\x12@\n" +
	"\fcreate_lease\x18\x02 \x01(\v2\x1b.raftlog.CreateLeaseCommandH\x00R\vcreateLease\x12=\n" +
	"\vrenew_lease\x18\x03 \x01(\v2\x1a.raftlog.RenewLeaseCommandH\x00R\n" +
	"renewLease\x12@\n" +
	"\facquire_lock\x18\x04 \x01(\v2\x1b.raftlog.AcquireLockCommandH\x00R\vacquireLock\x12@\n" +
	"\frelease_lock\x18\x05 \x01(\v2\x1b.raftlog.ReleaseLockCommandH\x00R\vreleaseLock\x12@\n" +
	"\fexpire_lease\x18\x06 \x01(\v2\x1b.raftlog.ExpireLeaseCommandH\x00R\vexpireLease\x12I\n" +
	"\x0fupsert_endpoint\x18\a \x01(\v2\x1e.raftlog.UpsertEndpointCommandH\x00R\x0eupsertEndpoint\x12I\n" +
	"\x0fremove_endpoint\x18\b \x01(\v2\x1e.raftlog.RemoveEndpointCommandH\x00R\x0eremoveEndpointB\t\n" +
	"\apayload*\x89\x02\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COMMAND_TYPE_CREATE_LEASE\x10\x01\x12\x1c\n" +
	"\x18COMMAND_TYPE_RENEW_LEASE\x10\x02\x12\x1d\n" +
	"\x19COMMAND_TYPE_ACQUIRE_LOCK\x10\x03\x12\x1d\n" +
	"\x19COMMAND_TYPE_RELEASE_LOCK\x10\x04\x12\x1d\n" +
	"\x19COMMAND_TYPE_EXPIRE_LEASE\x10\x05\x12 \n" +
	"\x1cCOMMAND_TYPE_UPSERT_ENDPOINT\x10\x06\x12 \n" +
	"\x1cCOMMAND_TYPE_REMOVE_ENDPOINT\x10\aB,Z*github.com/Mfon-19/clavis/internal/raftlogb\x06proto3"

var (
	file_internal_raftlog_command_proto_rawDescOnce sync.Once
	file_internal_raftlog_command_proto_rawDescData []byte
)

func file_internal_raftlog_command_proto_rawDescGZIP() []byte {
	file_internal_raftlog_command_proto_rawDescOnce.Do(func() {
		file_internal_raftlog_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_raftlog_command_proto_rawDesc), len(file_internal_raftlog_command_proto_rawDesc)))
	})
	return file_internal_raftlog_command_proto_rawDescData
}

var file_internal_raftlog_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_raftlog_command_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_raftlog_command_proto_goTypes = []any{
	(CommandType)(0),              // 0: raftlog.CommandType
	(*CreateLeaseCommand)(nil),    // 1: raftlog.CreateLeaseCommand
	(*RenewLeaseCommand)(nil),     // 2: raftlog.RenewLeaseCommand
	(*AcquireLockCommand)(nil),    // 3: raftlog.AcquireLockCommand
	(*ReleaseLockCommand)(nil),    // 4: raftlog.ReleaseLockCommand
	(*ExpireLeaseCommand)(nil),    // 5: raftlog.ExpireLeaseCommand
	(*UpsertEndpointCommand)(nil), // 6: raftlog.UpsertEndpointCommand
	(*RemoveEndpointCommand)(nil), // 7: raftlog.RemoveEndpointCommand
	(*CommandWrapper)(nil),        // 8: raftlog.CommandWrapper
}
var file_internal_raftlog_command_proto_depIdxs = []int32{
	0, // 0: raftlog.CommandWrapper.type:type_name -> raftlog.CommandType
	1, // 1: raftlog.CommandWrapper.create_lease:type_name -> raftlog.CreateLeaseCommand
	2, // 2: raftlog.CommandWrapper.renew_lease:type_name -> raftlog.RenewLeaseCommand
	3, // 3: raftlog.CommandWrapper.acquire_lock:type_name -> raftlog.AcquireLockCommand
	4, // 4: raftlog.CommandWrapper.release_lock:type_name -> raftlog.ReleaseLockCommand
	5, // 5: raftlog.CommandWrapper.expire_lease:type_name -> raftlog.ExpireLeaseCommand
	6, // 6: raftlog.CommandWrapper.upsert_endpoint:type_name -> raftlog.UpsertEndpointCommand
	7, // 7: raftlog.CommandWrapper.remove_endpoint:type_name -> raftlog.RemoveEndpointCommand
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_internal_raftlog_command_proto_init() }
func file_internal_raftlog_command_proto_init() {
	if File_internal_raftlog_command_proto != nil {
		return
	}
	file_internal_raftlog_command_proto_msgTypes[7].OneofWrappers = []any{
		(*CommandWrapper_CreateLease)(nil),
		(*CommandWrapper_RenewLease)(nil),
		(*CommandWrapper_AcquireLock)(nil),
		(*CommandWrapper_ReleaseLock)(nil),
		(*CommandWrapper_ExpireLease)(nil),
		(*CommandWrapper_UpsertEndpoint)(nil),
		(*CommandWrapper_RemoveEndpoint)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_raftlog_command_proto_rawDesc), len(file_internal_raftlog_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_raftlog_command_proto_goTypes,
		DependencyIndexes: file_internal_raftlog_command_proto_depIdxs,
		EnumInfos:         file_internal_raftlog_command_proto_enumTypes,
		MessageInfos:      file_internal_raftlog_command_proto_msgTypes,
	}.Build()
	File_internal_raftlog_command_proto = out.File
	file_internal_raftlog_command_proto_goTypes = nil
	file_internal_raftlog_command_proto_depIdxs = nil
}
